pipeline {
  agent { label 'jenkins-slave-linux-server' }
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:20-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
